Feature/6/modify element controller/element validation
kode-konveyor/repo-server pull request #38
Opened 2020-04-25 07:29 UTC by mayankus

2020-04-27 14:43 UTC, szirbucz commented
@magwas  it seems, there is an error in the model

2020-04-28 07:05 UTC, szirbucz commented
You have code coverage problems
```
ERROR: unit coverage miss at com.kodekonveyor.repo.api.ModifyElementController.checkNotFoundServer
ERROR: unit coverage miss at com.kodekonveyor.repo.api.ModifyElementController.checkFoundLocal
ERROR: unit coverage miss at com.kodekonveyor.repo.api.ModifyElementController.checkSyntax
```
You can run coverage test by right click on the project -> coverage as -> JUnit test. Check which lines are not covered and try to update your tests to cover them.

2020-04-28 11:26 UTC, szirbucz approved these changes

2020-04-28 11:26 UTC, szirbucz commented on .classpath
> +	<classpathentry kind="output" path="target/classes"/>
Revert this file to the state of the develop branch https://stackoverflow.com/questions/33951869/how-to-copy-a-file-from-one-branch-to-another-branch-using-functionality-on-ecli

2020-04-28 11:26 UTC, szirbucz commented on .settings/org.eclipse.jdt.core.prefs
>  org.eclipse.jdt.core.compiler.debug.localVariable=generate
revert this file to the state of develop branch (see my comment at .classpath)

2020-04-28 11:26 UTC, szirbucz commented on src/main/java/com/kodekonveyor/repo/api/CheckReferenceResultEnum.java
> +
Too much new lines

2020-04-28 11:26 UTC, szirbucz commented on src/main/java/com/kodekonveyor/repo/api/CheckReferenceResultEnum.java
> +
Remove empty line

2020-04-28 11:26 UTC, szirbucz commented on src/main/java/com/kodekonveyor/repo/api/ConstraintException.java
> +
Remove empty lines

2020-04-28 11:26 UTC, szirbucz commented on src/main/java/com/kodekonveyor/repo/api/ElementDTO.java
> +
Remove empty line

2020-04-28 11:26 UTC, szirbucz commented on src/main/java/com/kodekonveyor/repo/api/ElementEntity.java
> +
Remove empty line

2020-04-28 11:26 UTC, szirbucz commented on src/main/java/com/kodekonveyor/repo/api/ElementModificationDTO.java
> +
Remove empty line

2020-04-28 11:26 UTC, szirbucz commented on src/main/java/com/kodekonveyor/repo/api/ElementRepository.java
> +
Remove 2 empty lines

2020-04-28 11:26 UTC, szirbucz commented on src/main/java/com/kodekonveyor/repo/api/ElementWithRelationsDTO.java
> +
Remove empty line

2020-04-28 11:26 UTC, szirbucz commented on src/main/java/com/kodekonveyor/repo/api/ModificationDTO.java
> +
Remove empty line

2020-04-28 11:26 UTC, szirbucz commented on src/main/java/com/kodekonveyor/repo/api/ModifyElementController.java
> +
Remove empty line

2020-04-28 11:26 UTC, szirbucz commented on src/main/java/com/kodekonveyor/repo/api/ModifyElementController.java
> +
Remove empty line

2020-04-28 11:26 UTC, szirbucz commented on src/test/java/com/kodekonveyor/exception/ThrowableTester.java
> -      assertException(final Class<? extends Throwable> klass) {
whitespace only changes.

2020-04-28 11:26 UTC, szirbucz commented on src/test/java/com/kodekonveyor/exception/ThrowableTester.java
> +      fail("exception thrown"+ e);
Change it to `"exception thrown: " + e` (extend with space and colon)

2020-04-28 11:26 UTC, szirbucz commented on src/test/java/com/kodekonveyor/repo/api/ElementDTOTestData.java
> +    element.setId(FOUND_LOCAL_ID);
Code duplication. Create a private method for building ElementDTO
```
private ElementDTO buildElementDTO(
        final String id,
        final String commit,
        final String source,
        final String target
    ) {
    final ElementDTO element = new ElementDTO();

    element.setId(id);
    element.setCommit(commit);
    element.setSource(source);
    element.setTarget(target);

    return element;
}
```
And replace body of each get* method to a call of this method with the right parameters.

2020-04-28 11:26 UTC, szirbucz commented on src/test/java/com/kodekonveyor/repo/api/ElementEntityTestData.java
> +    final ElementEntity element = new ElementEntity();
Do the same here that you did in ElementDTOTestData to remove the duplications.

2020-04-28 11:26 UTC, szirbucz commented on src/test/java/com/kodekonveyor/repo/api/ModifyElementControllerElementValidationTest.java
> +
Too many empty lines

2020-04-28 11:26 UTC, szirbucz commented on src/test/java/com/kodekonveyor/repo/api/ModifyElementControllerTestBase.java
> +    doReturn(Optional.ofNullable(ElementEntityTestData.getFoundServer())).when(elementRepository).findById(ElementDTOTestData.FOUND_SERVER_ID);
The above 3 lines are repeated multiple times. Extract it to a method to reduce the code duplication.

2020-04-28 11:26 UTC, szirbucz commented on src/test/java/com/kodekonveyor/repo/api/ModifyElementControllerTestBase.java
> +    doReturn(CheckReferenceResultEnum.REMOTE).when(checkReferenceService).call(any(),Mockito.eq("sourceRemote"));
constants, like "sourceRemote", "targetNotFoundLocal", etc... should come from TestData

2020-04-28 20:40 UTC, szirbucz requested changes
The former approval was accidental. See the comments

2020-05-02 06:51 UTC, szirbucz requested changes

2020-05-02 06:51 UTC, szirbucz commented on .settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.javaFormatter=org.eclipse.jdt.core.defaultJavaFormatter
Revert these changes too

2020-05-11 11:30 UTC, magwas commented
I have resolved the conflicts for you. Please pull before push.

2020-05-13 06:51 UTC, magwas commented
closing due to inactivity

2020-05-13 06:51 UTC, closed without merging