Issue No-46 : LookupRepositoryByNameService/lookup repository by name
kode-konveyor/repo-server pull request #53
Opened 2020-07-19 13:50 UTC by Firdous18

2020-07-23 08:37 UTC, magwas requested changes
I have marked only some obvious problems.

2020-07-23 08:37 UTC, magwas commented on .settings/org.eclipse.jdt.core.prefs
>  org.eclipse.jdt.core.compiler.debug.localVariable=generate
settings should be changed only upon previous agreement

2020-07-23 08:37 UTC, magwas commented on .classpath
> -			<attribute name="org.eclipse.jst.component.dependency" value="/WEB-INF/lib"/>
What's the reason for this?

2020-07-23 08:37 UTC, magwas commented on .pmd
> +    <includeDerivedFiles>true</includeDerivedFiles>
what is the reason for this?

2020-07-23 08:37 UTC, magwas commented on src/main/java/com/kodekonveyor/repo/api/LerpoiEntity.java
> +  private String text;
The names of fields for a Lerpoi is name and description.

2020-08-04 09:11 UTC, szirbucz reviewed
Please call your mentor of @magwas if you need help.

2020-08-04 09:11 UTC, szirbucz commented on src/main/java/com/kodekonveyor/repo/api/SumtiEntityRepository.java
> +  Optional<SumtiEntity> findByLerpoi(LerpoiEntity lerpoiEntity);
One Lerpoi can belong to more sumtis, therefore you need to return List here instead of Optional.

2020-08-04 09:11 UTC, szirbucz commented on src/main/java/com/kodekonveyor/repo/backend/api/lookup/LookupRepositoryByNameService.java
> +    sumtiDTO.setUuid(sumtiEnity.get().getUuid());
Please extract the DTO conversion to a separate method.

2020-08-04 09:11 UTC, szirbucz commented on src/test/java/com/kodekonveyor/repo/backend/api/lookup/LookupRepositoryByNameServiceLookupRepositoryByNameTest.java
> +    SumtiEntityRepositoryStubs.behaviour(sumtiEntityRepository);
Call the behaviour method from the setup method of the LookupRepositoryByNameServiceTestBase.

2020-08-04 09:11 UTC, szirbucz requested changes
See above

2020-08-18 08:19 UTC, szirbucz requested changes
Please fix all the commented sections (@magwas' comments as well)

2020-08-18 08:19 UTC, szirbucz commented on src/main/java/com/kodekonveyor/repo/backend/api/lookup/LookupRepositoryByNameService.java
> +      throw new ValidationException(SumtiConstants.LERPOI_NOT_FOUND_EXCEPTION);
Please return empty list instead of throwing exception.

2020-08-18 08:19 UTC, szirbucz commented on src/main/java/com/kodekonveyor/repo/backend/api/lookup/LookupRepositoryByNameService.java
> +      throw new ValidationException(SumtiConstants.SUMTI_NOT_FOUND_EXCEPTION);
Please return empty list instead of throwing exception.

2023-04-23 08:35 UTC, closed without merging